giselles-ai/docs

README.md, mint.json
=> Init for Giselle

introduction.mdx
=> Update the Introduction page

mint.json, quickstart.mdx
Images for explanation have not been added.
They will be added in a separate PR.
=> Create a "Quickstart" page

guides/what-is-a-node.mdx, mint.json
I plan to add the image files for explanation in a separate PR.
=> Create "What is a node?" page

releases/product-notes.mdx
=> Update the Product Notes page

models/providers/google.mdx
- https://github.com/giselles-ai/giselle/pull/715
✨ This document update was generated by [giselles.ai](https://giselles.ai/).
=> Add `gemini-2.5-pro-preview-03-25`

models/providers/google.mdx
- https://github.com/giselles-ai/giselle/pull/745
✨ This document update was generated by [giselles.ai](https://giselles.ai/).
=> Add gemini-2.5-Flash-preview-04-17 and modify gemini-2.0-flash

guides/workspaces/integrate.mdx
- ref: https://github.com/giselles-ai/giselle/pull/682
=> Add details about GitHub Comment Attribution

models/providers/openai.mdx
refs: https://platform.openai.com/docs/models
=> Updated to match the structure of the official OpenAI documentation

models/providers/openai.mdx
- https://github.com/giselles-ai/giselle/pull/729
📝 Releated blog posts:
- [Giselle Now Supports OpenAI o3 & o4\-mini, Unlocking Next\-Level Reasoning \- Giselle: AI App Builder](https://giselles.ai/blog/giselle-now-supports-openai-o3-o4-mini)
=> Update docs for supporting OpenAI o3 & o4-mini

models/providers/anthropic.mdx
- https://github.com/giselles-ai/giselle/pull/764
=> Giselle supports reasoning option for Claude 3.7 Sonnet

models/providers/perplexity.mdx
- https://github.com/giselles-ai/giselle/pull/833
- https://github.com/giselles-ai/giselle/pull/836
=> Perplexity Node Now Supports Search Domain Filter Option

glossary/node.mdx
=> Updated to the latest information - /glossary/node

glossary/node.mdx
- https://github.com/giselles-ai/giselle/pull/1003
=> Docs: Add Node Duplication feature documentation

glossary/node.mdx
*   https://github.com/giselles-ai/giselle/pull/755
*   https://github.com/giselles-ai/giselle/pull/766
*   https://github.com/giselles-ai/giselle/pull/805
=> Docs: Trigger Node

glossary/trigger-node.mdx, mint.json
*   https://github.com/giselles-ai/giselle/pull/755
*   https://github.com/giselles-ai/giselle/pull/766
*   https://github.com/giselles-ai/giselle/pull/853
*   https://github.com/giselles-ai/giselle/pull/856
*   https://github.com/giselles-ai/giselle/pull/1000
=> docs: Create /glossary/trigger-node page and add manual trigger node

glossary/trigger-node.mdx
*   https://github.com/giselles-ai/giselle/pull/755
*   https://github.com/giselles-ai/giselle/pull/785
*   https://github.com/giselles-ai/giselle/pull/805
*   https://github.com/giselles-ai/giselle/pull/827
*   https://github.com/giselles-ai/giselle/pull/829
*   https://github.com/giselles-ai/giselle/pull/853
*   https://github.com/giselles-ai/giselle/pull/856
*   https://github.com/giselles-ai/giselle/pull/880
*   https://github.com/giselles-ai/giselle/pull/891
*   https://github.com/giselles-ai/giselle/pull/894
*   https://github.com/giselles-ai/giselle/pull/901
*   https://github.com/giselles-ai/giselle/pull/904
*   https://github.com/giselles-ai/giselle/pull/906
*   https://github.com/giselles-ai/giselle/pull/907
* …
=> docs: Add GitHub Trigger Node

glossary/action-node.mdx
=> Update Action Node Documentation with Get Discussion Example

glossary/trigger-node.mdx
=> Update Trigger Node Documentation

models/providers/google.mdx
This pull request updates the Google AI Models Overview documentation.
=> Update Google AI Models Overview

models/providers/anthropic.mdx
This PR updates the `anthropic.mdx` file with the latest model information.
=> Update Anthropic Docs

glossary/github-vector-store-node.mdx, mint.json
This PR adds documentation for the GitHub Vector Store Node.
=> feat: add documentation for GitHub Vector Store Node

glossary/node.mdx
=> Update /glossary/node - GitHub Vector Store Node & Query Node

glossary/postgresql-tools.mdx, mint.json
This PR adds documentation for PostgreSQL tools.
=> feat: add documentation for postgresql tools

glossary/text-node.mdx, mint.json
This PR adds documentation for the Text Node.
=> feat: add documentation for Text Node

models/providers/anthropic.mdx
This pull request updates the Anthropic models documentation.
=> docs: update anthropic models

glossary/github-tools.mdx
Add comprehensive parameter documentation for all GitHub API tools including:
- Required and optional parameters for each tool
- Parameter types and constraints
- Detailed descriptions for better usage understanding
- Structured format for improved readability
=> docs: expand GitHub tools documentation with detailed parameter specifications

glossary/github-tools.mdx
This pull request updates the documentation for GitHub Tools as requested.
=> Update documentation for GitHub Tools

glossary/github-vector-store-node.mdx
docs: update github-vector-store-node.mdx
=> docs: update github-vector-store-node.mdx
